### ISSUE TITLE
'NoneType' object has no attribute 'as_chat_engine'

### ISSUE THREAD

**Issue by chong5u** [ayaansh-roy/voice_assistant_llm#3]
(voice_llm) D:\ai\voice_llm>python app.py
pygame 2.5.2 (SDL 2.28.3, Python 3.11.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
Error while creating knowledgebase: File D:\dev\aiml\projects\git\voice_assistant_llm\rag\restaurant_file.txt does not exist.
Traceback (most recent call last):
  File "D:\ai\voice_llm\app.py", line 14, in <module>
    ai_assistant = AIVoiceAssistant()
                   ^^^^^^^^^^^^^^^^^^
  File "D:\ai\voice_llm\rag\AIVoiceAssistant.py", line 20, in __init__
    self._create_chat_engine()
  File "D:\ai\voice_llm\rag\AIVoiceAssistant.py", line 24, in _create_chat_engine
    self._chat_engine = self._index.as_chat_engine(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'as_chat_engine'

**Comment by AmineHamzaoui** [comment]
Hello, did you find a solution ?

**Comment by AmineHamzaoui** [comment]
You need to pull qdrant docker image with docker run
